= Лабораторна робота №4

*Тема:* якість коду (code quality) та автоматичне тестування веб-затосунків.

*Мета:* впровадити ESLint та Prettier для дотримання єдиного стилю коду.
Налаштувати та використовувати ці інструменти для перевірки та форматування свого коду.
Впровадити в проєкт автоматичне тестування за допомогою Mocha.

*Вимоги до звіту:*

. Кожен коміт у репозиторії GitHub має проходити перевірку ESLint та форматування за допомогою Prettier.
. У репозиторії має бути налаштований Husky для запуску перевірок перед комітом, що допоможе автоматизувати контроль якості перед внесенням змін до репозиторію.
. Має бути представлений приклад автоматичного тестування з використанням Mocha.
. Кожне завдання має бути виконане в окремій гілці github репозиторію студента.
Здійснити merge всіх гілок (без видалення) в main.

*Завдання:*

. За основу проєкту необхідно взяти результати лабораторної роботи №3 (Застосунок управління бібліотекою).
. Налаштувати та впровадити Prettier для форматування коду.
Використати налаштування для забезпечення консистентного стилю написання коду.
. Встановити ESLint для перевірки коду на відповідність стандартам.
Налаштувати ESLint для роботи з TypeScript та Prettier.
. Налаштувати Husky для запуску перевірки ESLint та тестів перед кожним комітом.
. Впровадження автоматичного тестування за допомогою Mocha.
Реалізувати юніт-тести для ключових методів класів Library та Validation.

*Корисні посилання:*

. https://uk.javascript.info/code-quality
. https://prettier.io/docs/en/
. https://eslint.org/docs/latest/
. https://freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/
. https://mochajs.org/.