= Лабораторна робота №9-10

*Тема:* Розробка e-commerce застосунку базі API Platzi Fake Store

*Мета:* розробити застосунку для електронної комерції, який використовує API Platzi Fake Store для отримання, фільтрації та відображення продуктів.

*Вимоги до звіту:*

. Лабораторна робота повинна бути виконана *в новому репозиторію* vue-ecommerce-app github репозиторію студента.
. При написанні застосунку, використати паттерн репозиторій (Repository).
. Дотримання TypeScript-типізації;
. Використання Composition Api або Options Api на вибір студента;
. Під час написання застосунку, обов'язково дотримуватись https://ua.vuejs.org/style-guide/[style guide];
. Якщо ви використовуєте css бібліотеку, то імпортуйте тільки необхідні стилі (базові, кнопки, таблиці, поля тощо).
Виористовуйте scss.
. Використовуйте Eslint;
. Для управляння станом ввиокритовуйте Pinia.
. Завершений проєкт повинен бути завантажений на GitHub та gh-pages з детальною документацією щодо встановлення та використання.

== Практична частина

=== Завдання:

** Проаналізувати схеми даних для Products, Filter Products, Categories (https://fakeapi.platzi.com/en/about/introduction/[Platzi Fake Store API], https://api.escuelajs.co/docs[Swagger Docs]).
** Ініціалізуйте новий проєкт з використанням https://vuejs.org/guide/quick-start.html#creating-a-vue-application[create-vue]
** Налаштуйте базову структуру проєкту, включаючи компоненти, ui-бібліотеки, маршрутизацію та стани.
** Виконайте інтеграцію з REST API Platzi Fake Store.
Забезпечте обробку помилок при запитах до API.
** Реалізуйте пагінацію для списку продуктів.
Додайте кнопки "Наступна" та "Попередня" для навігації між сторінками.
** Додайте можливість фільтрації товарів за назвою (введення в текстове поле), ціною (введення мінімальної та максимальної ціни), категорією (вибір з випадаючого списку).
Всі параметри фільтрації повинні зберігатися в URL.
** Створіть простий і зрозумілий інтерфейс.
Використовуйте CSS-фреймворки (Bootstrap або Tailwind CSS на вибір студента) для стилізації.