== Workflow для команди з 3 студентів

*Команда: 3 студенти*

*Ролі:*

* *Team Lead*: 1 студент (відповідає за управління проєктом, комунікацію та координацію команди)
* *Developer 1*: 1 студент (відповідає за фронтенд-розробку, UI/UX: реалізувати компоненти для відображення продуктів, фільтрів і пагінації і т.д.)
* *Developer 2*: 1 студент (відповідає за інтеграцію з API: реалізувати функції для роботи з API (отримання продуктів, категорій, фільтрація і т.д.)

*Організація роботи*

. Команда проводить першу зустріч для обговорення вимог проєкт, визначення цілей та розподілу ролей.
. Установіть кінцеві терміни для основних етапів проєкт.
. Розділіть проєкт на спринти, (наприклад, 1 тиждень).
. Визначте завдання для кожного спринту, включаючи конкретні етапи розробки та тестування.
. Team Lead координує зустрічі для перевірки прогресу.
. Розробники працюють над своїми завданнями та підтримують один одного в процесі.
. Дотримання git workflow (branches: main, dev (for testing), feature branches, PR) з code review від Team Lead.
. Презентація проєкту на gh-pages.