= Лабораторна робота №7

*Тема:* Основи роботи з компонентами: props, event handling, watchers

*Мета:* засвоїти основи роботи з компонентами у Vue.js, зокрема використання props, event handling, watchers.

*Вимоги до звіту:*

. Лабораторна роба повинна бути виконана *в окремій гілці* - feature/split-on-components у vue-lottery-app github репозиторію студента.
. Поділ застосунку на компоненти;
. Дотримання TypeScript-типізації;
. Використання Composition Api або Options Api на вибір студента;
. Під час написання застосунку, обов'язково дотримуватись https://ua.vuejs.org/style-guide/[style guide];
. Використовуйте Eslint;
. Заборонено використовувати alert для показу помилок юзеру.

== Практична частина

=== Самостійна робота студента:

. https://ua.vuejs.org/guide/components/props.html[Реквізити];
. https://ua.vuejs.org/guide/components/events.html[Події компонентів];
. https://ua.vuejs.org/guide/essentials/watchers.html[Спостерігачі];
. https://ua.vuejs.org/guide/components/slots.html[Слоти]
. https://ua.vuejs.org/examples/#grid[Приклад створення багаторазового компонента таблиці та його використання із зовнішніми даними.]
. https://ua.vuejs.org/examples/#modal[Модальний компонент із настроюваними слотами та переходами CSS.]

=== Завдання:

Використовуючи застосунок vue-lottery-app, лабораторної роботи №6, виконати наступне:

. Поділ на компоненти:
** Компонент кнопка;
** Компонент поля вводу;
** Компонент переможця;
** Компонент блоку списку переможців;
** Компонент блоку форми реєстрації;
** Компонент блоку таблиці з учасниками;

. Додати новий функціонал
** Додати зберігання юзерів у localStorage.
** Редагування учасника.
Додати в кінці таблиці ще один стовпець, де розмістити кнопку "Редагувати дані".
При кліку на кнопку повинно відкритися модальне вікно з формою (форма повинна проходити валідацію), де поля вводу повинні бути заповнені даними користувача.
Нижче повинна бути кнопка "Оновити дані", клік по якій призведе до оновлення даних учасника у таблиці та закриттю модального вікна.
Модальне вікно повинно бути в окремому компоненті Modal (css стилі можна взяти з обраної UI бібліотеки).
** Видалення учасника.
Додати в кінці таблиці ще один стовпець, де розмістити кнопку "Видалити учасника".
При кліку на кнопку повинно відкритися модальне вікно, в якому юзер має підтвердити видалення користувача: "Ви дійсно бажаєте видалити учасника {{name}}, {{email}}?".
Нижче розмістити кнопки "Так" (видаляє учасника), "Ні" (просто закриває модальне вікно).
** Сортування.
У таблиці учасників додати можливість сортувати за іменем (A-Z) та датою народження.
Додати відповідні контроли з іконками, наприклад, https://icons.getbootstrap.com/icons/sort-alpha-down/[Sort alpha down], https://icons.getbootstrap.com/icons/sort-down/[Sort down], які реагуватимуть на дїї користувача.
** Фільтрація.
Додати поле для пошуку учасників за іменем.
Це поле повинно бути в окремому компоненті SearchBar, який передає подію filter-by-name до батьківського компонента, і фільтрує список у таблиці на основі введених даних.
** Унікальність e-mail.
Перед додаванням учасника в таблицю, потрібно перевірити, чи існує вже учасник з такою ж електронною поштою.
Якщо такий учасник є, потрібно вивести повідомлення про помилку.
** Додати ключові модифікатори для прослуховування подій клавіатури (коли юзер натискає enter на клавіатурі при роботі з формою реєстрації) та Esc, щоб закрити модальне вікно.

